### ISSUE TITLE
Centos 6.9 jdk 1.8.0_171 mysql 5.6启动datax_admin报错

### ISSUE THREAD

**Issue by user99999** [WeiYe-Jing/datax-web#163]
Centos 6.9 jdk 1.8.0_171 mysql 5.6启动datax_admin报错

相关信息：

04:59:53.591 admin [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$1afbf0e9] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
04:59:53.785 admin [main] ERROR o.s.b.c.l.LoggingApplicationListener - Cannot set level '/opt/datax-web-2.1.2/modules/datax-admin/bin/../data/applogs/admin' for 'path'
 :: Spring Boot ::        (v2.1.4.RELEASE)

04:59:53.810 admin [main] INFO  c.w.d.a.DataXAdminApplication - No active profile set, falling back to default profiles: default
04:59:55.217 admin [main] ERROR o.s.b.SpringApplication - Application run failed
java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.security.servlet.SecurityRequestMatcherProviderAutoConfiguration$MvcRequestMatcherConfiguration

Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration] from ClassLoader [sun.misc.Launcher$AppClassLoader@7cd84586]

Caused by: java.lang.SecurityException: class "javax.servlet.DispatcherType"'s signer information does not match signer information of other classes in the same package

[centos 6 启动 datax-admin 报错.txt](https://github.com/WeiYe-Jing/datax-web/files/4809524/centos.6.datax-admin.txt)

**Comment by WeiYe-Jing** [comment]
项目是自己打包的吗？还是用的官方提供的包

**Comment by user99999** [comment]
用的官方提供的包，v2.1.2

**Comment by WeiYe-Jing** [comment]
> 用的官方提供的包，v2.1.2

下载jar包的时间还记得吗

**Comment by WeiYe-Jing** [comment]
> > 用的官方提供的包，v2.1.2
> 
> 下载jar包的时间还记得吗，上周五更新过了一版，是不是最新的

**Comment by WeiYe-Jing** [comment]
> > > 用的官方提供的包，v2.1.2
> > 
> > 
> > 下载jar包的时间还记得吗，06-19号更新过了一版，是不是最新的

**Comment by user99999** [comment]
昨天晚上下载的

**Comment by King-Star-Queen** [comment]
刚刚又重新下载部署了一遍，启动datax-admin依旧报这种错误

**Comment by King-Star-Queen** [comment]
jdk：1.8.0_252
Python：2.6.6
mysql：5.7.24
maven：3.6.3
datax是阿里官网     环境有问题吗

**Comment by WeiYe-Jing** [comment]
> jdk：1.8.0_252
> Python：2.6.6
> mysql：5.7.24
> maven：3.6.3
> datax是阿里官网 环境有问题吗

Centos版本号也发下

**Comment by WeiYe-Jing** [comment]
针对报错已上传了修复版本，有空可以帮忙测试并反馈下

**Comment by King-Star-Queen** [comment]
datax-admin已经成功启动

**Comment by claro5** [comment]
windows2012 用idea运行 DataXAdminApplication 提示 ERROR o.s.b.c.l.LoggingApplicationListener - Cannot set level './data/applogs/admin' for 'path'

详细信息如下:
09:31:42.966 admin [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$d63d69e5] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
09:31:43.297 admin [main] ERROR o.s.b.c.l.LoggingApplicationListener - Cannot set level './data/applogs/admin' for 'path'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.4.RELEASE)

09:31:43.377 admin [main] INFO  c.w.d.a.DataXAdminApplication - No active profile set, falling back to default profiles: default
09:31:44.928 admin [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.wugui.datax.admin.DataXAdminApplication]; nested exception is java.lang.IllegalStateException: Error processing condition on org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration$DifferentManagementContextConfiguration
09:31:44.939 admin [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
09:31:44.947 admin [main] ERROR o.s.b.SpringApplication - Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.wugui.datax.admin.DataXAdminApplication]; nested exception is java.lang.IllegalStateException: Error processing condition on org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration$DifferentManagementContextConfiguration
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:599)
	at org.springframework.context.annotation.ConfigurationClassParser.access$900(ConfigurationClassParser.java:108)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.lambda$processGroupImports$1(ConfigurationClassParser.java:808)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:804)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:774)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:185)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at com.wugui.datax.admin.DataXAdminApplication.main(DataXAdminApplication.java:22)
Caused by: java.lang.IllegalStateException: Error processing condition on org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration$DifferentManagementContextConfiguration
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:218)
	at org.springframework.context.annotation.ConfigurationClassParser.processMemberClasses(ConfigurationClassParser.java:361)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:263)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:589)
	... 17 common frames omitted
Caused by: java.lang.IllegalArgumentException: Circular placeholder reference 'server.port' in property definitions
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:139)
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:160)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:237)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:211)
	at org.springframework.core.env.AbstractPropertyResolver.resolveNestedPlaceholders(AbstractPropertyResolver.java:228)
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:88)
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:68)
	at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:550)
	at org.springframework.boot.actuate.autoconfigure.web.server.ManagementPortType.getPortProperty(ManagementPortType.java:66)
	at org.springframework.boot.actuate.autoconfigure.web.server.ManagementPortType.get(ManagementPortType.java:54)
	at org.springframework.boot.actuate.autoconfigure.web.server.OnManagementPortCondition.getMatchOutcome(OnManagementPortCondition.java:53)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
	... 23 common frames omitted

Process finished with exit code 1
