### ISSUE TITLE
增量同步（根据时间戳进行同步），变量替换{${lastTime}) ，(${currentTime}）时，sql执行出现问题。

### ISSUE THREAD

**Issue by kanbuq** [WeiYe-Jing/datax-web#198]
具体问题描述为，[读取数据库数据失败. 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select * from emp where FROM_UNIXTIME(operationDate) >= FROM_UNIXTIME(${lastTime}) and operationDate < FROM_UNIXTIME(${currentTime}) 具体错误信息为：com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{lastTime}) and operationDate < FROM_UNIXTIME(${currentTime})' ，
增量时间字段为：-D${lastTime}=%s -D${currentTime}=%s
json字段为：
      "querySql": [
                  "select * from emp where FROM_UNIXTIME(operationDate) >= FROM_UNIXTIME(${lastTime}) and operationDate < FROM_UNIXTIME(${currentTime})"
                ]

**Comment by WeiYe-Jing** [comment]
配置错误，建议多仔细文档
https://github.com/WeiYe-Jing/datax-web/blob/master/doc/datax-web/time-increment-desc.md

**Comment by kanbuq** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WeiYe"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月9日(星期四) 上午9:28
收件人:&nbsp;"WeiYe-Jing/datax-web"<datax-web@noreply.github.com&gt;;
抄送:&nbsp;"🤦‍♂️"<315663895@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WeiYe-Jing/datax-web] 增量同步（根据时间戳进行同步），变量替换{${lastTime}) ，(${currentTime}）时，sql执行出现问题。 (#198)





 
配置错误，建议多仔细文档
 https://github.com/WeiYe-Jing/datax-web/blob/master/doc/datax-web/time-increment-desc.md

**Comment by WeiYe-Jing** [comment]
配置可以截个图看看

**Comment by kanbuq** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WeiYe"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月9日(星期四) 上午9:49
收件人:&nbsp;"WeiYe-Jing/datax-web"<datax-web@noreply.github.com&gt;;
抄送:&nbsp;"🤦‍♂️"<315663895@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WeiYe-Jing/datax-web] 增量同步（根据时间戳进行同步），变量替换{${lastTime}) ，(${currentTime}）时，sql执行出现问题。 (#198)





 
配置可以截个图看看

**Comment by kanbuq** [comment]
[https://www.jianshu.com/p/7935b4c555ce](url) 具体的配置如下

**Comment by kanbuq** [comment]
![24049333-2daae2ede98ef834](https://user-images.githubusercontent.com/33740650/86990041-4ef00d00-c1ce-11ea-980f-7f5cc6176567.jpg)
![24049333-7d80ee898c8d26b0](https://user-images.githubusercontent.com/33740650/86990045-531c2a80-c1ce-11ea-87a4-397bec5bf981.jpg)
![24049333-5c41001a5a5e1c85](https://user-images.githubusercontent.com/33740650/86990060-56afb180-c1ce-11ea-800c-61079dd18a2c.jpg)
![24049333-7d80ee898c8d26b0](https://user-images.githubusercontent.com/33740650/86990064-58797500-c1ce-11ea-86b5-c4d1dfe05c98.jpg)
### 本机的具体配置为如下所示。

**Comment by kanbuq** [comment]
![24049333-2daae2ede98ef834](https://user-images.githubusercontent.com/33740650/86990254-c6be3780-c1ce-11ea-9940-ae2e78509833.jpg)
### 本机的具体配置如下所示

![24049333-5c41001a5a5e1c85](https://user-images.githubusercontent.com/33740650/86990205-a2625b00-c1ce-11ea-89c5-44552b0772e3.jpg)
![24049333-7d80ee898c8d26b0](https://user-images.githubusercontent.com/33740650/86990211-a68e7880-c1ce-11ea-87c7-f181a33fe337.jpg)
![24049333-7466d80274454e18](https://user-images.githubusercontent.com/33740650/86990215-a8f0d280-c1ce-11ea-9e4d-121a17d9c7d5.jpg)

**Comment by WeiYe-Jing** [comment]
![image](https://user-images.githubusercontent.com/33245094/86990476-3fbd8f00-c1cf-11ea-8175-21b43dcd18de.png)
上面发你的文档看样子你并没有去看，https://github.com/WeiYe-Jing/datax-web/blob/master/doc/datax-web/time-increment-desc.md
文档截图中的参数不是这样配置的，一点要参考文档

**Comment by WeiYe-Jing** [comment]
问题解决了吗？

**Comment by kanbuq** [comment]
问题得到了解决，最后增量时间字段为：-DlastTime='%s' -DcurrentTime='%s'，需要记得加冒号，下面的sql语句为
"select * from emp where operationDate >= FROM_UNIXTIME(${lastTime}) and operationDate < FROM_UNIXTIME(${currentTime})"，字段名一致，感谢。

**Comment by fu-xin** [comment]
oracle转mysql，oracle日期字段类型为date，mysql为datetime类型，增量迁移 报类型转换错误


2020-09-06 12:43:36.665 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Finished read record by Sql: [select * from agent."TB_TESTX" where updated_at >= '1599365051' / (60 * 60 * 24) + TO_DATE('1970-01-01 08:00:00', 'YYYY-MM-DD HH:MI:SS') and updated_at < '1599367409' / (60 * 60 * 24) + TO_DATE('1970-01-01 08:00:00', 'YYYY-MM-DD HH:MI:SS')
2020-09-06 12:43:36 [AnalysisStatistics.analysisStatisticsLog-53] ] jdbcUrl:[jdbc:oracle:thin:@//192.168.2.90:1521/ORCL].
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 2020-09-06 12:43:37.567 [0-0-0-writer] WARN  CommonRdbmsWriter$Task - 回滚此次写入, 采用每次写入一行方式提交. 因为:TIMESTAMP 类型转换错误：[{"byteSize":7,"rawData":"testXY1","type":"STRING"}]
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 2020-09-06 12:43:37.668 [0-0-0-writer] ERROR StdoutPluginCollector - 
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] java.sql.SQLException: TIMESTAMP 类型转换错误：[{"byteSize":7,"rawData":"testXY1","type":"STRING"}]
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:497) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:405) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doOneInsert(CommonRdbmsWriter.java:380) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:362) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:297) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.writer.mysqlwriter.MysqlWriter$Task.startWrite(MysqlWriter.java:78) [mysqlwriter-0.0.1-SNAPSHOT.jar:na]
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) [datax-core-0.0.1-SNAPSHOT.jar:na]
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 2020-09-06 12:43:37.671 [0-0-0-writer] ERROR StdoutPluginCollector - 脏数据: 
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] {"exception":"TIMESTAMP 类型转换错误：[{\"byteSize\":7,\"rawData\":\"testXY1\",\"type\":\"STRING\"}]","record":[{"byteSize":1,"index":0,"rawData":"1","type":"DOUBLE"},{"byteSize":7,"index":1,"rawData":"testXY1","type":"STRING"},{"byteSize":8,"index":2,"rawData":1599358896000,"type":"DATE"},{"byteSize":8,"index":3,"rawData":1599365529000,"type":"DATE"}],"type":"writer"}
2020-09-06 12:43:37 [AnalysisStatistics.analysisStatisticsLog-53] 2020-09-06 12:43:37.723 [taskGroup-0] INFO  TaskGroupContainer - taskGroup[0] taskId[0] is successed, used[1214]ms

**Comment by CLinPhone** [comment]
![Snipaste_2020-09-15_11-13-42](https://user-images.githubusercontent.com/43274438/93161191-9b167b00-f744-11ea-8371-0e2bcc12d1d4.png)
像数据表分表的配置，如何在json配置中实现

**Comment by WeiYe-Jing** [comment]
> ![Snipaste_2020-09-15_11-13-42](https://user-images.githubusercontent.com/43274438/93161191-9b167b00-f744-11ea-8371-0e2bcc12d1d4.png)
> 像数据表分表的配置，如何在json配置中实现

麻烦重新新建一个issue哈，方便让更多开发者参与讨论，这个主题是增量，别人很难看到下面在讨论这么有吸引力的功能。

**Comment by meihuaA0010** [comment]
hbase的增量任务‘增量时间段’这里需要怎么配置

**Comment by renjiutong** [comment]
com.wugui.datax.rpc.util.XxlRpcException: xxl-rpc response status invalid.

**Comment by JavaLearner** [comment]
你好，我这边创建任务，在配置where条件的时候加上了条件，但在生成JSON文件的时候，并没有加上where条件，请问是什么原因呢
![image](https://user-images.githubusercontent.com/19368585/147635077-dfce3ff2-709b-4a5f-aa24-452f3a45cfbf.png)

![image](https://user-images.githubusercontent.com/19368585/147635066-08b0dcd0-e0ff-4246-8c45-7c7cafe5af9b.png)

**Comment by sevenlvc** [comment]
根据主键自增，在第一次同步成功后，源表有新数据进行第二次同步，startId=12135,但是同步不成功，请大佬看看问题出在哪？谢谢！！！

![ER6EM{WRYVUPUPDXPUWN_K5](https://user-images.githubusercontent.com/55381544/156983500-7afbcd6e-b3c3-4534-8ab6-a55d72a5e5f8.png)

**Comment by sevenlvc** [comment]
根据主键自增，在第一次同步成功后，源表有新数据进行第二次同步，startId=12135,但是同步不成功，请大佬看看问题出在哪？谢谢！！！

![image](https://user-images.githubusercontent.com/55381544/156983669-3e385226-1927-44dc-8f28-43b66da5ee78.png)

![image](https://user-images.githubusercontent.com/55381544/156983818-59fad13c-eafc-4046-8cc4-71328b5de066.png)

![image](https://user-images.githubusercontent.com/55381544/156983910-1e0325f7-2428-40e0-b7c3-eac8607ea822.png)
