### ISSUE TITLE
添加Hbase 数据源时报错

### ISSUE THREAD

**Issue by OnsraZZZZZ** [WeiYe-Jing/datax-web#265]
Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/protobuf/generated/MasterProtos$MasterService$BlockingInterface

**Comment by WeiYe-Jing** [comment]
> Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/protobuf/generated/MasterProtos$MasterService$BlockingInterface

看下日志，是不是和 #134的问题一样

**Comment by WeiYe-Jing** [comment]
> Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/protobuf/generated/MasterProtos$MasterService$BlockingInterface

项目用的hbase版本是1.3.0，和你们环境匹配吗

**Comment by OnsraZZZZZ** [comment]
> > Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/protobuf/generated/MasterProtos$MasterService$BlockingInterface
> 
> 项目用的hbase版本是1.3.0，和你们环境匹配吗

我们用的版本是2.2.5

**Comment by WeiYe-Jing** [comment]
> > > Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/protobuf/generated/MasterProtos$MasterService$BlockingInterface
> > 
> > 
> > 项目用的hbase版本是1.3.0，和你们环境匹配吗
> 
> 我们用的版本是2.2.5

可以换下项目中hbase的版本然后重新打包。也可以在项目的安装包 admin 下面 lib中替换hbase jar.

**Comment by eaglesinchina** [comment]
我的hbase版本是1.2.0-cdh5.12.0，datax-web是2.1.2版本，添加Hbase数据源也报错，然后我把datax-admin里面的pom.xml里面的<artifactId>hbase-client</artifactId>依赖中被排除的<artifactId>hbase-protocol</artifactId>注释掉，然后就OK了

**Comment by WeiYe-Jing** [comment]
> 我的hbase版本是1.2.0-cdh5.12.0，datax-web是2.1.2版本，添加Hbase数据源也报错，然后我把datax-admin里面的pom.xml里面的hbase-client依赖中被排除的hbase-protocol注释掉，然后就OK了

2.1.3版本中hbase-client变更为
`<dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-client</artifactId>
            <version>${hbase.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>guava</artifactId>
                    <groupId>com.google.guava</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>commons-logging</artifactId>
                    <groupId>commons-logging</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>hadoop-auth</artifactId>
                    <groupId>org.apache.hadoop</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>hadoop-common</artifactId>
                    <groupId>org.apache.hadoop</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>hadoop-annotations</artifactId>
                    <groupId>org.apache.hadoop</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>slf4j-log4j12</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>`
方便的话帮忙验证下哈，感谢！

**Comment by y16899168** [comment]
@WeiYe-Jing 我的是hbase1.3.2 也是出现这个问题，把datax-admin里面的pom.xml里面的hbase-client依赖中被排除的hbase-protocol注释掉，重新打包之后，还是这样的错误。jar也换成hbase-client-1.3.2.jar 了，是我们那里操作有问题吗？

**Comment by y16899168** [comment]
有没有遇到这样错误的Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
        ... 127 common frames omitted
Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.hbase.zookeeper.ZKUtil.joinZNode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
        at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.setNodeNames(ZooKeeperWatcher.java:412)
        at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.<init>(ZooKeeperWatcher.java:177)
        at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.<init>(ZooKeeperWatcher.java:153)
        at org.apache.hadoop.hbase.client.ZooKeeperKeepAliveConnection.<init>(ZooKeeperKeepAliveConnection.java:43)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getKeepAliveZooKeeperWatcher(ConnectionManager.java:1702)
        at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:104)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:912)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:696)

**Comment by y16899168** [comment]
> 我的hbase版本是1.2.0-cdh5.12.0，datax-web是2.1.2版本，添加Hbase数据源也报错，然后我把datax-admin里面的pom.xml里面的hbase-client依赖中被排除的hbase-protocol注释掉，然后就OK了

您是直接在datax-admin-2.1.2.jar这个包中修改的吗？修改完成之后，重新打包了吗？

**Comment by WeiYe-Jing** [comment]
> > 我的hbase版本是1.2.0-cdh5.12.0，datax-web是2.1.2版本，添加Hbase数据源也报错，然后我把datax-admin里面的pom.xml里面的hbase-client依赖中被排除的hbase-protocol注释掉，然后就OK了
> 
> 您是直接在datax-admin-2.1.2.jar这个包中修改的吗？修改完成之后，重新打包了吗？

不是在这个jar下面，在lib下面

**Comment by y16899168** [comment]
您好：
首先太感谢您能够回复我邮件，再次表示感谢。
我的hadoop版本是2.7.7
hbase版本是1.3.2
还是有点不太明白，请在指教下，是这个路径下面的 datax-admin-2.1.2.jar 这个包下的pom.xml文件吗？







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WeiYe-Jing/datax-web"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月7日(星期一) 晚上6:52
收件人:&nbsp;"WeiYe-Jing/datax-web"<datax-web@noreply.github.com&gt;;
抄送:&nbsp;"海"<236795744@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [WeiYe-Jing/datax-web] 添加Hbase 数据源时报错 (#265)





   
我的hbase版本是1.2.0-cdh5.12.0，datax-web是2.1.2版本，添加Hbase数据源也报错，然后我把datax-admin里面的pom.xml里面的hbase-client依赖中被排除的hbase-protocol注释掉，然后就OK了
  
您是直接在datax-admin-2.1.2.jar这个包中修改的吗？修改完成之后，重新打包了吗？
  
不是在这个jar下面，在lib下面

**Comment by eaglesinchina** [comment]
> 您好： 首先太感谢您能够回复我邮件，再次表示感谢。 我的hadoop版本是2.7.7 hbase版本是1.3.2 还是有点不太明白，请在指教下，是这个路径下面的 datax-admin-2.1.2.jar 这个包下的pom.xml文件吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WeiYe-Jing/datax-web" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月7日(星期一) 晚上6:52 收件人:&nbsp;"WeiYe-Jing/datax-web"<datax-web@noreply.github.com&gt;; 抄送:&nbsp;"海"<236795744@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [WeiYe-Jing/datax-web] 添加Hbase 数据源时报错 (#265) 我的hbase版本是1.2.0-cdh5.12.0，datax-web是2.1.2版本，添加Hbase数据源也报错，然后我把datax-admin里面的pom.xml里面的hbase-client依赖中被排除的hbase-protocol注释掉，然后就OK了 您是直接在datax-admin-2.1.2.jar这个包中修改的吗？修改完成之后，重新打包了吗？ 不是在这个jar下面，在lib下面 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我是下载源码，然后用Idea打开这个项目，然后修改datax-admin模块下的pom.xml， 注释掉这个hbase-protocol依赖，然后重新编译打包，放到服务器上测试正常连接Hbase

**Comment by caoliang-web** [comment]
添加hbase数据源出现以下错误：
![image](https://user-images.githubusercontent.com/71004656/92572761-6f644280-f2b7-11ea-8fd2-78ba631e8dc7.png)

java.lang.reflect.InvocationTargetException
hbase-client已改成对应的版本，hbase-protocol已注释掉，本地调试没有问题，在服务器上就出现这样的问题

**Comment by WeiYe-Jing** [comment]
> 添加hbase数据源出现以下错误：
> ![image](https://user-images.githubusercontent.com/71004656/92572761-6f644280-f2b7-11ea-8fd2-78ba631e8dc7.png)
> 
> java.lang.reflect.InvocationTargetException
> hbase-client已改成对应的版本，hbase-protocol已注释掉，本地调试没有问题，在服务器上就出现这样的问题

本地调试和服务器上的数据源配置完全一样吗

**Comment by caoliang-web** [comment]
是一样的

**Comment by y16899168** [comment]
这个问题我是这样处理的：
1、如果报Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/protobuf/generated/MasterProtos$MasterService$BlockingInterface
这个错误，需要把lib包下的datax-admin里面的pom.xml里面的hbase-client依赖中被排除的hbase-protocol注释掉就可以


2、如果报空指针需要把hbase-client*.jar 换为 对应的hbase的版本，并且把hbase-zookeeper-2.0.0.jar 注释掉，以为zookper冲突了。
然后确认hbase和datax-web中的zk连的是一个就OK了。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "WeiYe-Jing/datax-web"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 下午5:04
收件人:&nbsp;"WeiYe-Jing/datax-web"<datax-web@noreply.github.com&gt;;
抄送:&nbsp;"海"<236795744@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [WeiYe-Jing/datax-web] 添加Hbase 数据源时报错 (#265)





 
是一样的

**Comment by caoliang-web** [comment]
你说的把hbase-zookeeper-2.0.0.jar 注释掉是直接删除data-admin lib下的hbase-zookeeper-2.0.0.jar这个包吗

**Comment by y16899168** [comment]
对，直接删除。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WeiYe-Jing/datax-web"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月10日(星期四) 下午5:24
收件人:&nbsp;"WeiYe-Jing/datax-web"<datax-web@noreply.github.com&gt;;
抄送:&nbsp;"海"<236795744@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [WeiYe-Jing/datax-web] 添加Hbase 数据源时报错 (#265)





 
你说的把hbase-zookeeper-2.0.0.jar 注释掉是直接删除data-admin lib下的hbase-zookeeper-2.0.0.jar这个包吗

**Comment by caoliang-web** [comment]
更试了，好了，谢了

**Comment by caoliang-web** [comment]
添加hive出现Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).]. - 具体错误信息为：java.sql.SQLException: Method not supported，是怎么回事呢

**Comment by kaybinwong** [comment]
这个应该是hive版本不一致导致的，有没有办法自定义Hadoop版本？

**Comment by lijianzhong001** [comment]
> 这个问题我是这样处理的： 1、如果报Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/protobuf/generated/MasterProtos$MasterService$BlockingInterface 这个错误，需要把lib包下的datax-admin里面的pom.xml里面的hbase-client依赖中被排除的hbase-protocol注释掉就可以 2、如果报空指针需要把hbase-client*.jar 换为 对应的hbase的版本，并且把hbase-zookeeper-2.0.0.jar 注释掉，以为zookper冲突了。 然后确认hbase和datax-web中的zk连的是一个就OK了。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "WeiYe-Jing/datax-web" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月9日(星期三) 下午5:04 收件人:&nbsp;"WeiYe-Jing/datax-web"<datax-web@noreply.github.com&gt;; 抄送:&nbsp;"海"<236795744@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [WeiYe-Jing/datax-web] 添加Hbase 数据源时报错 (#265) 是一样的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，您是下载的tar.gz包，还是源码编译的？

**Comment by caoliang-web** [comment]
源码编译的

**Comment by lazy05** [comment]
你好：
       为什么在添加hbase数据源时 一直提示
Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/protobuf/generated/MasterProtos$MasterService$BlockingInterface    这样的错误

**Comment by nglszhaosi** [comment]
这个问题我也遇到了，不需要多麻烦，直接把hbase/lib下的hbase-client-2.0.5.jar和hbase-commom-2.0.5.jar 放到datax-web-2.1.2/modules/datax-admin/lib下面，原本那两个1.3.0的jar包删除就行了

**Comment by nglszhaosi** [comment]
> 这个问题我也遇到了，不需要多麻烦，直接把hbase/lib下的hbase-client-2.0.5.jar和hbase-commom-2.0.5.jar 放到datax-web-2.1.2/modules/datax-admin/lib下面，原本那两个1.3.0的jar包删除就行了

然后重启
