### ISSUE TITLE
构建的json模板问题导致datax任务执行失败

### ISSUE THREAD

**Issue by xuyanhua** [WeiYe-Jing/datax-web#304]
* 背景：
oracle数据库，从A表同步数据到A'表
* 系统构建的模板为：
```json
{
  "job": {
    "setting": {
      "speed": {
        "channel": 3,
        "byte": 1048576
      },
      "errorLimit": {
        "record": 0,
        "percentage": 0.02
      }
    },
    "content": [
      {
        "reader": {
          "name": "oraclereader",
          "parameter": {
            "username": "***",
            "password": "***",
            "column": [
              "\"ID\"",
              "\"USER_ID\"",
              "\"EMAIL\"",
              "\"ORG_ID\"",
              "\"PROJECT_ID\"",
              "\"PROJECT_NAME\"",
              "\"VIZ_TYPE\"",
              "\"VIZ_ID\"",
              "\"VIZ_NAME\"",
              "\"SUB_VIZ_ID\"",
              "\"SUB_VIZ_NAME\"",
              "\"START_TIME\"",
              "\"END_TIME\""
            ],
            "splitPk": "",
            "connection": [
              {
                "table": [
                  "STATISTIC_DURATION"
                ],
                "jdbcUrl": [
                  "jdbc:oracle:thin:@//localhost:1521/helowin"
                ]
              }
            ]
          }
        },
        "writer": {
          "name": "oraclewriter",
          "parameter": {
             "username": "***",
            "password": "***",
            "column": [
              "\"ID\"",
              "\"USER_ID\"",
              "\"EMAIL\"",
              "\"ORG_ID\"",
              "\"PROJECT_ID\"",
              "\"PROJECT_NAME\"",
              "\"VIZ_TYPE\"",
              "\"VIZ_ID\"",
              "\"VIZ_NAME\"",
              "\"SUB_VIZ_ID\"",
              "\"SUB_VIZ_NAME\"",
              "\"START_TIME\"",
              "\"END_TIME\""
            ],
            "connection": [
              {
                "table": [
                  "STATISTIC_DURATION_2"
                ],
                "jdbcUrl": "jdbc:oracle:thin:@//localhost:1521/helowin"
              }
            ]
          }
        }
      }
    ]
  }
}
```
* 执行报错
```bash
2020-09-10 07:47:38.226 [job-0] INFO  JobContainer - jobContainer starts to do prepare ...
 2020-09-10 07:47:38.227 [job-0] INFO  JobContainer - DataX Reader.Job [oraclereader] do prepare work .
 2020-09-10 07:47:38.227 [job-0] INFO  JobContainer - DataX Writer.Job [oraclewriter] do prepare work .
 2020-09-10 07:47:38.228 [job-0] INFO  JobContainer - jobContainer starts to do split ...
 2020-09-10 07:47:38.235 [job-0] ERROR JobContainer - Exception when job run
 com.alibaba.datax.common.exception.DataXException: Code:[Framework-03], Description:[DataX引擎配置错误，该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 在有总bps限速条件下，单个channel的bps值不能为空，也不能为非正数
 	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
 	at com.alibaba.datax.core.job.JobContainer.adjustChannelNumber(JobContainer.java:430) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
 	at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:387) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
 	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
 	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
 	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
 2020-09-10 07:47:38.243 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
 2020-09-10 07:47:38.288 [job-0] ERROR Engine - 
 
 经DataX智能分析,该任务最可能的错误原因是:
 com.alibaba.datax.common.exception.DataXException: Code:[Framework-03], Description:[DataX引擎配置错误，该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 在有总bps限速条件下，单个channel的bps值不能为空，也不能为非正数
 	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
 	at com.alibaba.datax.core.job.JobContainer.adjustChannelNumber(JobContainer.java:430)
 	at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:387)
 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
 	at com.alibaba.datax.core.Engine.start(Engine.java:92)
 	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
 	at com.alibaba.datax.core.Engine.main(Engine.java:204)
 
2020-09-10 07:47:38 [JobThread.run-165] <br>----------- datax-web job execute end(finish) -----------<br>----------- ReturnT:ReturnT [code=500, msg=command exit value(1) is failed, content=null]
2020-09-10 07:47:38 [TriggerCallbackThread.callbackLog-186] <br>----------- datax-web job callback finish.
```
网上查资料发现限速配置有问题：
[Datax限速bug](https://zhmin.github.io/2018/12/16/datax-ratelimiter-bug/)

**Comment by chaozhangpower** [comment]
移除 "byte": 1048576

**Comment by yeahsyoung** [comment]
> 移除 "byte": 1048576
大佬，这个问题我改了代码，通过设置默认的channel.speed来解决，能贡献代码么

**Comment by jiayb** [comment]
代碼裡 這個類的DataxJsonHelper  這一句注釋掉speedMap.putAll(ImmutableMap.of("channel", 3, "byte", 1048576));

**Comment by Arther1228** [comment]
2.1.3-alpha-relase版本，
speedMap.putAll(ImmutableMap.of("channel", 3, "byte", 1048576));
暂时改为
speedMap.putAll(ImmutableMap.of("channel", 3));
即可。
