### ISSUE TITLE
[使用mongodb插件] 一直报参数不合法，手写json脚本无误

### ISSUE THREAD

**Issue by czetao** [WeiYe-Jing/datax-web#378]
这是使用data-web生成的jon
 {
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 	"content":[
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 		{
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 			"reader":{
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 				"name":"mongodbreader",
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 				"parameter":{
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 					"collectionName":"test_table",
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 					"column":[
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 						{
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 							"name":"word",
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 							"type":"String"
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 						},
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 						{
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 							"name":"cnt",
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 							"type":"String"
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 						}
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 					"dbName":"dataX_test",
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 					"userName":"",
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 					"userPassword":""
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 				}
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 			},

这是错误提示
-53] com.alibaba.datax.common.exception.DataXException: ILLEGAL_VALUE - 不合法参数
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.reader.mongodbreader.util.MongoUtil.initMongoClient(MongoUtil.java:22) ~[mongodbreader-0.0.1-SNAPSHOT.jar:na]
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.reader.mongodbreader.MongoDBReader$Job.init(MongoDBReader.java:49) ~[mongodbreader-0.0.1-SNAPSHOT.jar:na]
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
2020-11-11 16:57:55 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]

**Comment by FuJian1105** [comment]
解决了吗？什么原因？
