### ISSUE TITLE
logback.xml 配置错误 ，

### ISSUE THREAD

**Issue by jiayb** [WeiYe-Jing/datax-web#444]
Caused by: java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file] - Failed to create parent directories for [/data/datax-web-2.1.2/packages/datax-executor/bin/..//./data/applogs/executor/jobhandler/datax-executor.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file] - openFile(./data/applogs/executor/jobhandler/datax-executor.log,true) call failed. java.io.FileNotFoundException: ./data/applogs/executor/jobhandler/datax-executor.log (没有那个文件或目录)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
        at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:67)
        at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:57)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:117)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:297)
        ... 14 more
解决办法：<property name="LOG_PATH"
              value="${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/data/applogs/executor/jobhandler}}}" /> 修改成<property name="LOG_PATH"
              value="${log_path:-${LOG_TEMP:-${java.io.tmpdir:-/data/applogs/executor/jobhandler}}}" />

**Comment by jiayb** [comment]
datax-web  2.1.2 版本

**Comment by xiaolongnayun** [comment]
请问这个错误怎么解决啊

**Comment by hqm1988** [comment]
请问这个错误怎么解决啊

**Comment by bugmaker1220** [comment]
请问能说一下解决办法吗

**Comment by LaoRay-Hub** [comment]
同求解决办法

**Comment by RubyXun** [comment]
> 同求解决办法

#690

**Comment by RubyXun** [comment]
> 请问能说一下解决办法吗

#690

**Comment by RubyXun** [comment]
> 请问能说一下解决办法吗

#690

**Comment by RubyXun** [comment]
> 请问这个错误怎么解决啊

#690
