### ISSUE TITLE
com.wugui.datax.rpc.util.XxlRpcException: io.netty.channel.AbstractChannel$AnnotatedConnectException: 拒绝连接: 

### ISSUE THREAD

**Issue by magic20191** [WeiYe-Jing/datax-web#470]
任务触发类型：手动触发
调度机器：10.0.0.67
执行器-注册方式：手动录入
执行器-地址列表：[10.0.0.67]
路由策略：第一个
阻塞处理策略：单机串行
任务超时时间：0
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：10.0.0.67
code：500
msg：com.wugui.datax.rpc.util.XxlRpcException: io.netty.channel.AbstractChannel$AnnotatedConnectException: 拒绝连接: /10.0.0.67:80 at com.wugui.datax.rpc.remoting.invoker.reference.XxlRpcReferenceBean.lambda$getObject$0(XxlRpcReferenceBean.java:260) at com.sun.proxy.$Proxy172.run(Unknown Source) at com.wugui.datax.admin.core.trigger.JobTrigger.runExecutor(JobTrigger.java:241) at com.wugui.datax.admin.core.trigger.JobTrigger.processTrigger(JobTrigger.java:188) at com.wugui.datax.admin.core.trigger.JobTrigger.trigger(JobTrigger.java:84) at com.wugui.datax.admin.core.thread.JobTriggerPoolHelper.lambda$addTrigger$0(JobTriggerPoolHelper.java:85) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: 拒绝连接: /10.0.0.67:80 at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ... 1 more Caused by: java.net.ConnectException: 拒绝连接 ... 11 more

这是为什么啊，调度器报错了，找不到原因

**Comment by luyan-max** [comment]
我也是，修改了任务的一些信息后再手动执行。就报这个错误。
