### ISSUE TITLE
[QUESTION]  Cannot run program "python": error=2, No such file or directory

### ISSUE THREAD

**Issue by bingfenglai** [WeiYe-Jing/datax-web#512]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**

I can run python in linux terminal, but the program execution task reports the above error.

**Which version of DataX Web:**
latest

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by fenbujue** [comment]
请问老哥解决了吗 我遇到了一样的问题

**Comment by sunrongpu** [comment]
我也是
2022-08-09 15:17:44 [JobThread.run-130] <br>----------- datax-web job execute start -----------<br>----------- Param:
2022-08-09 15:17:44 [BuildCommand.buildDataXParam-100] ------------------Command parameters:
2022-08-09 15:17:44 [ExecutorJobHandler.execute-83] java.io.IOException: Cannot run program "python": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:633)
	at java.lang.Runtime.exec(Runtime.java:498)
	at com.wugui.datax.executor.service.jobhandler.ExecutorJobHandler.execute(ExecutorJobHandler.java:55)
	at com.wugui.datatx.core.thread.JobThread.run(JobThread.java:153)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more

2022-08-09 15:17:44 [JobThread.run-165] <br>----------- datax-web job execute end(finish) -----------<br>----------- ReturnT:ReturnT [code=500, msg=command exit value(-1) is failed, content=null]
2022-08-09 15:17:44 [TriggerCallbackThread.callbackLog-186] <br>----------- datax-web job callback finish.

**Comment by yinuan-i** [comment]
which python看下是不是别名，是的话就去datax-executor项目的BuildCommand类第39行左右，把我的是把原本cmdArr.add("python");的改为cmdArr.add("python3");后就正常了

**Comment by RubyXun** [comment]
python:
  path: /usr/bin/python
