### ISSUE TITLE
Mac aarch64 运行executor executor ExecutorRegistryThread" java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/hp/jb28x8qj3z7crl5ssf8tl6cc0000gn/T/jna-400106789/jna750014645081268444.tmp

### ISSUE THREAD

**Issue by dalayy** [WeiYe-Jing/datax-web#680]
mac 运行executor 时报错：Exception in thread "datax-web, executor ExecutorRegistryThread" java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/hp/jb28x8qj3z7crl5ssf8tl6cc0000gn/T/jna-400106789/jna750014645081268444.tmp
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1823)
	at java.lang.Runtime.load0(Runtime.java:782)
	at java.lang.System.load(System.java:1098)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2130)
	at oshi.hardware.platform.mac.MacCentralProcessor.<clinit>(MacCentralProcessor.java:53)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getProcessor(MacHardwareAbstractionLayer.java:53)
	at com.wugui.datatx.core.util.OSUtils.cpuUsage(OSUtils.java:99)
	at com.wugui.datatx.core.thread.ExecutorRegistryThread.lambda$start$0(ExecutorRegistryThread.java:44)
	at java.lang.Thread.run(Thread.java:750)

通过file  /var/folders/hp/jb28x8qj3z7crl5ssf8tl6cc0000gn/T/jna-400106789/jna750014645081268444.tmp 查看，发现文件是x86架构，可是我的jvm 是aarch64的，有没有大佬知道怎么处理

**Comment by dalayy** [comment]
开始以为是jna 版本太低，升级之后还是有问题

**Comment by riruigit** [comment]
我的 m1 pro 也是这样

**Comment by riruigit** [comment]
后面有找到解决方案吗？
